version: "3"

services:
  zipkin:
    image: openzipkin/zipkin:2.21.0
    ports:
      - "9411:9411"
    networks:
      - crawler_app
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  fluentd:
    image: seeker00837149/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - crawler_app
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
 
  elasticsearch:
    image: elasticsearch:8.1.3
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data        
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - crawler_app
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.key == mon        

  kibana:
    image: kibana:8.1.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    
    ports:
      - "5601:5601"
    networks:
      - crawler_app
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  elasticsearch-data:

networks:
  crawler_app:
    external:
      name: crawler_app
