global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
 receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - send_resolved: true
    username: 'crawler_bot'
    channel: '#dmitriy_berezikov'
