version: "3"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8020:8080
    networks:
      - docker_app
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
        - prometheus_data:/prometheus
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - ./alertmanager/alert.rules:/etc/prometheus/alert.rules
    networks:
      - docker_app
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  alertmanager: 
     image: prom/alertmanager 
     volumes:
        - ./alertmanager/alertmanager.yml:/alertmanager.yml
     command: 
      - '--config.file=/alertmanager.yml' 
     ports: 
      - 9093:9093 
     networks:
      - docker_app

  grafana:
    image: grafana/grafana-oss:8.5.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=gfadmin
      - GF_SECURITY_ADMIN_PASSWORD=crawler
    networks:
      - docker_app  
    ports:
      - 3000:3000

volumes:
  prometheus_data:
  grafana_data:

networks:
  docker_appnet:
    external:
      name: docker_app
