version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017
    networks:
      - app
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.db == true 

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=crawler
      - RABBITMQ_DEFAULT_PASS=123456789
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.db == true 

  crawler:
    image: seeker00837149/crawler
    restart: on-failure
    environment:
      - MONGO=mongodb
      - MONGO_PORT=27017
      - RMQ_HOST=rabbitmq
      - RMQ_QUEUE=crawler
      - RMQ_USERNAME=crawler
      - RMQ_PASSWORD=123456789
      - CHECK_INTERVAL=20
      - EXCLUDE_URLS=.*github.com
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - app
    deploy:
      mode: replicated      
      replicas: 3
      restart_policy:
        condition: on-failure

  ui:
    image: seeker00837149/web_ui
    restart: on-failure
    environment:
      - MONGO=mongodb
      - MONGO_PORT=27017
    ports:
      - 80:8000
    depends_on:
      - mongodb
      - crawler
    networks:
      - app
    deploy:
      mode: replicated      
      replicas: 2 
      restart_policy:
        condition: on-failure

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influx
    deploy:
      mode: global

volumes:
  mongo_db:
  rabbitmq_data:
  rabbitmq_log:

networks:
  app:
