---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/ubuntu/app
    state: directory
    mode: '0755'

- name: Copy directory of microservices
  copy:
    src: ../app/docker-stack.yml
    dest: /home/ubuntu/app

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: crawler
    compose:
    - /home/ubuntu/app/docker-stack.yml
