---
- name: Initialize Docker Swarm
  docker_swarm:
    state: present
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}" 
  register: token

- name: Check directory for keep tokens and manager address
  file:
    path: ./tokens
    state: directory
  delegate_to: localhost

- name: Save manager token
  copy:
    dest: ./tokens/manager-token
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"
  delegate_to: localhost

- name: Save workers token
  copy:
    dest: ./tokens/worker-token
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
  delegate_to: localhost

- name: Save manager address
  copy:
    dest: ./tokens/manager-address
    content: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  delegate_to: localhost
