---
- name: Docker install
  hosts: all
  become: true
  roles:
    - docker-install
    
- name: Initialize Docker Swarm
  hosts: manager
  become: true
  roles:
    - swarm-init

- name: Add workers to the Swarm
  hosts: workers
  become: true
  roles:
    - workers-join
