---
- name: Docker install
  hosts: all
  become: true
  roles:
    - docker-install
    
- name: Initialize Docker Swarm
  hosts: manager
  become: true
  roles:
    - swarm-init

- name: Add workers to the Swarm
  hosts: workers
  become: true
  roles:
    - workers-join
    
- name: Add db node label
  hosts: manager
  become: true
  roles:
    - node-label-db 

- name: Deploy applications
  hosts: manager
  become: true
  roles:
    - app-deploy 

