---
- name: Docker install
  hosts: all
  become: true
  roles:
    - docker-install
    
- name: Initialize Docker Swarm
  hosts: manager
  become: true
  roles:
    - swarm-init

- name: Add workers to the Swarm
  hosts: workers
  become: true
  roles:
    - workers-join

- name: Add monitoring as manager
  hosts: manager
  become: true
  roles:
    - manager-add

- name: Add db node label
  hosts: manager
  become: true
  roles:
    - node-label-db 

- name: Add mon node label
  hosts: manager
  become: true
  roles:
    - node-label-mon 

- name: Deploy applications
  hosts: manager
  become: true
  roles:
    - app-deploy 

- name: Deploy monitoring 
  hosts: monitoring
  become: true
  roles:
    - mon-deploy
